apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderator-be
  namespace: tasayco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-moderator-be
  template:
    metadata:
      labels:
        app: content-moderator-be
    spec:
      containers:
      - name: content-moderator-be
        image: luistasayco2004/hackathon_luistasayco_backend:definit
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials              
              key: DATABASE_URL                      
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
        - name: TOKEN_API
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: TOKEN_API