apiVersion: v1
kind: Service
metadata:
  name: content-moderator-be
  namespace: tasayco
spec:
  type: NodePort   
  ports:
  - port: 30001     
    targetPort: 8080 
    nodePort: 30001
  selector:
    app: content-moderator-be