server:
  port: 8080

spring:
  application:
    name: reniec-service
  r2dbc:
    url: r2dbc:postgresql://ep-restless-sky-a51geef6.us-east-2.aws.neon.tech/neondb?sslmode=require
    # r2dbc:postgresql://ep-aged-wind-a5enixuk.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    # neondb_owner
    password: BMHmq2suYZ7d
    # 4yAJol2zpRgk
  contentmoderator:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imp1bGlvLnF1aXNwZUB2YWxsZWdyYW5kZS5lZHUucGUifQ.6M-P2QMMvKFZEeMvTUXvkOooM02N_pWqt0OdlaYW3PM
    # eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imp1bGlvLnF1aXNwZUB2YWxsZWdyYW5kZS5lZHUucGUifQ.6M-P2QMMvKFZEeMvTUXvkOooM02N_pWqt0OdlaYW3PM
